# Generated by Django 4.0.1 on 2022-02-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
