# Generated by Django 4.0.1 on 2022-02-15 21:59

from django.db import migrations, models
import django.db.models.deletion

def create_categories(apps, pouet):
    Category = apps.get_model('auctions', 'Category')
    Listing = apps.get_model('auctions', 'Listing')
    for listing in Listing.objects.all():
        category = Category.objects.filter(name=listing.category).first()
        if category is None:
            category = Category(name=listing.category)
            category.save()
        listing.category = category.id 
        listing.save(update_fields=['category'])
        
class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_listing_id_watchlist_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RunPython(create_categories),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
